import type { Assessment } from "./types";

/** Static example. It is NOT generated by Gemini and the UI labels it as a demo. */
export const DEMO_RESULT: Assessment = {
  problem: "Damaged electrical socket with burn marks",
  riskLevel: "HIGH",
  detectedHazards: [
    "Possible overheating or arcing inside the socket",
    "Risk of electric shock if the faceplate or slots are touched",
    "Possible fire risk if the outlet stays in use",
  ],
  visualEvidence: [
    "Dark discoloration around the lower slots",
    "Scorch-like marks spreading across the faceplate",
    "A visible crack or damaged area near the right-hand slot",
  ],
  possibleCause:
    "Based on the visible evidence, the socket may have overheated or arced, possibly from a loose connection, a damaged plug or an overloaded circuit. Only a qualified electrician can confirm the cause.",
  immediateSafetyAdvice: [
    "Avoid touching the damaged area.",
    "Stop using the outlet and keep children and pets away from it.",
    "If the breaker panel is dry and reachable without going near the socket, switch off the circuit for that outlet.",
    "If you see smoke or sparks, or smell burning, leave the area and call your local emergency number.",
  ],
  safeChecks: [
    "From a distance, note whether the marks are only on the faceplate or also on the wall.",
    "Note whether other outlets or lights on the same circuit behave oddly.",
    "Write down when the problem started and what was plugged in, to tell the electrician.",
  ],
  doNotAttempt: [
    "Do not open the faceplate or touch exposed wiring.",
    "Do not tape over, patch or cover the damage.",
    "Do not plug anything into this outlet or unplug anything from it.",
    "Do not use water on or near the socket.",
  ],
  professionalHelp: true,
  professionalReason:
    "Burn marks on a socket can point to wiring faults hidden behind the wall. A licensed electrician should inspect and repair it before it is used again.",
  summary:
    "Based on the visible evidence, this socket shows damage and discoloration that suggest overheating. Treat it as unsafe, stop using it and arrange a professional electrical inspection.",
};
